# SPDX-License-Identifier: zlib-acknowledgement

# NOTE(Ryan): Verify locally:
# $(circleci config validate)
# $(circleci local execute)

version: 2.1

jobs:
  lint-and-test:
    docker:
      - image: python
    steps:
      - checkout
      - run:
          name: Dependencies
          command: |
            pip3 install -r misc/requirements.txt
      - run:
          name: Linting
          command: |
            pylint --rcfile='misc/.pylintrc' -- **/*.py
      - run:
          name: Testing
          command: |
            coverage run --branch -m pytest tests/ 
            coverage report --show-missing --fail-under 100

workflows:
  cad:
    jobs:
      - lint-and-test
