# SPDX-License-Identifier: zlib-acknowledgement

version: 2.1

orbs:
  python: circleci/python@1.4.0

jobs:
  lint-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: Linting
          command: |
            pylint --rcfile='misc/.pylintrc' -- **/*.py
      - run:
          name: Testing
          command: |
            coverage run --branch -m pytest tests/ 
            coverage report --show-missing --fail-under 100

workflows:
  cad:
    jobs:
      - lint-and-test
